### ISSUE TITLE
分布式训练问题

### ISSUE THREAD

**Issue by QAQXS** [zhouchenlin2096/Spikingformer#5]
/home/liuchang/.conda/envs/Lizhuo3.9/lib/python3.9/site-packages/torch/distributed/launch.py:181: FutureWarning: The module torch.distributed.launch is deprecated
and will be removed in future. Use torchrun.
Note that --use-env is set by default in torchrun.
If your script expects `--local-rank` argument to be set, please
change it to read from `os.environ['LOCAL_RANK']` instead. See
https://pytorch.org/docs/stable/distributed.html#launch-utility for
further instructions

  warnings.warn(
WARNING:torch.distributed.run:
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************
Traceback (most recent call last):
  File "/home/liuchang/SNN/Spikingformer-master/cifar10/train.py", line 952, in <module>
    main()
  File "/home/liuchang/SNN/Spikingformer-master/cifar10/train.py", line 338, in main
    args, args_text = _parse_args()
  File "/home/liuchang/SNN/Spikingformer-master/cifar10/train.py", line 323, in _parse_args
    with open(args_config.config, 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'cifar10.yml'
Traceback (most recent call last):
  File "/home/liuchang/SNN/Spikingformer-master/cifar10/train.py", line 952, in <module>
    main()
  File "/home/liuchang/SNN/Spikingformer-master/cifar10/train.py", line 338, in main
    args, args_text = _parse_args()
  File "/home/liuchang/SNN/Spikingformer-master/cifar10/train.py", line 323, in _parse_args
    with open(args_config.config, 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'cifar10.yml'
Traceback (most recent call last):
  File "/home/liuchang/SNN/Spikingformer-master/cifar10/train.py", line 952, in <module>
    main()
  File "/home/liuchang/SNN/Spikingformer-master/cifar10/train.py", line 338, in main
    args, args_text = _parse_args()
  File "/home/liuchang/SNN/Spikingformer-master/cifar10/train.py", line 323, in _parse_args
    with open(args_config.config, 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'cifar10.yml'
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 319362) of binary: /home/liuchang/.conda/envs/Lizhuo3.9/bin/python
Traceback (most recent call last):
  File "/home/liuchang/.conda/envs/Lizhuo3.9/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/liuchang/.conda/envs/Lizhuo3.9/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/liuchang/.conda/envs/Lizhuo3.9/lib/python3.9/site-packages/torch/distributed/launch.py", line 196, in <module>
    main()
  File "/home/liuchang/.conda/envs/Lizhuo3.9/lib/python3.9/site-packages/torch/distributed/launch.py", line 192, in main
    launch(args)
  File "/home/liuchang/.conda/envs/Lizhuo3.9/lib/python3.9/site-packages/torch/distributed/launch.py", line 177, in launch
    run(args)
  File "/home/liuchang/.conda/envs/Lizhuo3.9/lib/python3.9/site-packages/torch/distributed/run.py", line 785, in run
    elastic_launch(
  File "/home/liuchang/.conda/envs/Lizhuo3.9/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/liuchang/.conda/envs/Lizhuo3.9/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 250, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError:
============================================================
/home/liuchang/SNN/Spikingformer-master/cifar10/train.py FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2023-11-08_16:20:18
  host      : gpu-PowerEdge-T640
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 319364)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[2]:
  time      : 2023-11-08_16:20:18
  host      : gpu-PowerEdge-T640
  rank      : 2 (local_rank: 2)
  exitcode  : 1 (pid: 319365)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-11-08_16:20:18
  host      : gpu-PowerEdge-T640
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 319362)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
请问这个怎么解决

**Comment by zhouchenlin2096** [comment]
你用单卡训练就行，cifar 10， cifar100， dvs 128， cifar10-dvs四个数据集我都是单卡训练的，只有imagenet我是多卡训练的

**Comment by QAQXS** [comment]
&nbsp; 首先非常感谢您的回复，您的代码给了我一些启发。我将您使用的数据集更换成了自己的数据，因为数据集比较大，需要采用分布式训练。在训练中出现了以下问题，请问怎么解决。.
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 959125 closing signal SIGTERM
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 959124) of binary: /home/liuchang/.conda/envs/SNN/bin/python
Traceback (most recent call last):
&nbsp; File "/home/liuchang/.conda/envs/SNN/lib/python3.9/runpy.py", line 197, in _run_module_as_main
&nbsp; &nbsp; return _run_code(code, main_globals, None,
&nbsp; File "/home/liuchang/.conda/envs/SNN/lib/python3.9/runpy.py", line 87, in _run_code
&nbsp; &nbsp; exec(code, run_globals)
&nbsp; File "/home/liuchang/.conda/envs/SNN/lib/python3.9/site-packages/torch/distributed/launch.py", line 193, in <module&gt;
&nbsp; &nbsp; main()
&nbsp; File "/home/liuchang/.conda/envs/SNN/lib/python3.9/site-packages/torch/distributed/launch.py", line 189, in main
&nbsp; &nbsp; launch(args)
&nbsp; File "/home/liuchang/.conda/envs/SNN/lib/python3.9/site-packages/torch/distributed/launch.py", line 174, in launch
&nbsp; &nbsp; run(args)
&nbsp; File "/home/liuchang/.conda/envs/SNN/lib/python3.9/site-packages/torch/distributed/run.py", line 752, in run
&nbsp; &nbsp; elastic_launch(
&nbsp; File "/home/liuchang/.conda/envs/SNN/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 131, in __call__
&nbsp; &nbsp; return launch_agent(self._config, self._entrypoint, list(args))
&nbsp; File "/home/liuchang/.conda/envs/SNN/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 245, in launch_agent
&nbsp; &nbsp; raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError:&nbsp;
============================================================
train.py FAILED




风萧萧兮*易水寒
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zhouchenlin2096/Spikingformer"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年11月13日(星期一) 上午10:21
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [zhouchenlin2096/Spikingformer] 分布式训练问题 (Issue #5)





 
你用单卡训练就行，cifar 10， cifar100， dvs 128， cifar10-dvs四个数据集我都是单卡训练的，只有imagenet我是多卡训练的
